services:
  paste:
    image: ghcr.io/jabuxas/abyss:latest
    # build: .
    ports:
      - "3235:3235"
    volumes:
      - ./files:/app/files

      # Optional overrides for themes
      # - ./custom:/app/assets:ro
    env_file:
      - .env
    tmpfs:
      # in case big files for uploads before saving
      - /tmp
    restart: unless-stopped
