services:
  paste:
    image: ghcr.io/jabuxas/abyss:latest
    # build: .
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3235:3235"
    volumes:
      - ./files:/app/files

      # optional overrides for themes
      # - ./custom:/app/assets:ro
    env_file:
      - .env
    tmpfs:
      # in case big files for uploads before saving
      - /tmp
    restart: unless-stopped
