services:
  paste:
    image: git.jabuxas.com/jabuxas/abyss:latest
    ports:
      - "3235:3235"
    volumes:
      - ./files:/files
      # - ./dev/home:/static:ro
      # - ./dev/templates:/templates:ro
    env_file:
      - .env
    tmpfs:
      - /tmp
    restart: unless-stopped
