services:
  paste:
    image: ghcr.io/jabuxas/abyss:latest
    ports:
      - "3235:3235"
    volumes:
      - ./files:/files
      # You can customize the default by overriding the templates
      # - ./dev/home:/static:ro
      # - ./dev/templates:/templates:ro
    env_file:
      - .env
    tmpfs:
      # in case big files
      - /tmp
    restart: unless-stopped
