services:
  paste:
    image: git.jabuxas.xyz/jabuxas/abyss:latest
    ports:
      - "3235:3235"
    volumes:
      - ./files:/files
      - ./dev:/static:ro
    env_file:
      - .env
    restart: unless-stopped
