name: deploy the stuff

on:
  push:
    branches:
      - main

permissions: write-all
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [abyss]
        dockerfile: [Dockerfile]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Github registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          file: ${{ matrix.dockerfile }}
