name: Build and Push Docker Image (latest)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker-latest:
    name: Build and Push Docker Image (latest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Build Information for Docker
        id: build_info_docker
        run: |
          GIT_VERSION=$(git describe --tags --always --dirty=-dev 2>/dev/null || git rev-parse --short HEAD)-main
          GIT_COMMIT=$(git rev-parse HEAD)
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          BUILT_BY="github-actions-main-build"

          echo "DOCKER_APP_VERSION=${GIT_VERSION}" >> $GITHUB_ENV
          echo "DOCKER_GIT_COMMIT=${GIT_COMMIT}" >> $GITHUB_ENV
          echo "DOCKER_BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
          echo "DOCKER_BUILT_BY=${BUILT_BY}" >> $GITHUB_ENV

          echo "Docker Build Info: Version=${GIT_VERSION}, Commit=${GIT_COMMIT}, Date=${BUILD_DATE}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/abyss:latest
          build-args: |
            APP_VERSION=${{ env.DOCKER_APP_VERSION }}
            GIT_COMMIT=${{ env.DOCKER_GIT_COMMIT }}
            BUILD_DATE=${{ env.DOCKER_BUILD_DATE }}
            BUILT_BY=${{ env.DOCKER_BUILT_BY }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
