name: Build and Push Docker Image Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login git.jabuxas.xyz -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t git.jabuxas.xyz/jabuxas/abyss:${{ github.ref_name }} .
          docker push git.jabuxas.xyz/jabuxas/abyss:${{ github.ref_name }}

      - name: Log out of Docker registry
        run: docker logout git.jabuxas.xyz
